In [5]:
import numpy as np

a = np.arange(20).reshape(4, 5) # this will create an ndarray with 20 integers

a.ndim #displays the dimesion(axes) of the ndarray generated.
type(a)

numpy.ndarray

In [6]:
a.shape #size of the arrays in each dimensions

(4, 5)

In [11]:
a.size #number of element in the array

20

In [12]:
a.dtype #the data type of the element in the ndarray

dtype('int64')

In [13]:
a.itemsize #size of each element in the ndarray

8

In [7]:
a.data #buffer containing the actual elements.

In [9]:
b = np.array([2,3,4,5,3,12,65,32])
type(b)

numpy.ndarray

In [12]:
c = np.array([(1,2,6,54,65,54), (43,65,43,32,324,654), ("steve" , "muish", "mike", "fab", "school", 8)])
c

array([['1', '2', '6', '54', '65', '54'],
       ['43', '65', '43', '32', '324', '654'],
       ['steve', 'muish', 'mike', 'fab', 'school', '8']], dtype='<U21')

In [13]:
c.dtype

dtype('<U21')

In [22]:
d = np.empty((3,15))
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.empty((3,3))

array([[1.58218056e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [39]:
np.arange(.000001, 21.0000001, 1.5821) #np.arange(start, stop, difference between th enumbers.)

array([1.0000000e-06, 1.5821010e+00, 3.1642010e+00, 4.7463010e+00,
       6.3284010e+00, 7.9105010e+00, 9.4926010e+00, 1.1074701e+01,
       1.2656801e+01, 1.4238901e+01, 1.5821001e+01, 1.7403101e+01,
       1.8985201e+01, 2.0567301e+01])

In [45]:
np.linspace(0,2,999) #22 numbers from 0 to 2. linspace

array([0.        , 0.00200401, 0.00400802, 0.00601202, 0.00801603,
       0.01002004, 0.01202405, 0.01402806, 0.01603206, 0.01803607,
       0.02004008, 0.02204409, 0.0240481 , 0.0260521 , 0.02805611,
       0.03006012, 0.03206413, 0.03406814, 0.03607214, 0.03807615,
       0.04008016, 0.04208417, 0.04408818, 0.04609218, 0.04809619,
       0.0501002 , 0.05210421, 0.05410822, 0.05611222, 0.05811623,
       0.06012024, 0.06212425, 0.06412826, 0.06613226, 0.06813627,
       0.07014028, 0.07214429, 0.0741483 , 0.0761523 , 0.07815631,
       0.08016032, 0.08216433, 0.08416834, 0.08617234, 0.08817635,
       0.09018036, 0.09218437, 0.09418838, 0.09619238, 0.09819639,
       0.1002004 , 0.10220441, 0.10420842, 0.10621242, 0.10821643,
       0.11022044, 0.11222445, 0.11422846, 0.11623246, 0.11823647,
       0.12024048, 0.12224449, 0.1242485 , 0.12625251, 0.12825651,
       0.13026052, 0.13226453, 0.13426854, 0.13627255, 0.13827655,
       0.14028056, 0.14228457, 0.14428858, 0.14629259, 0.14829

In [49]:
np.random

<module 'numpy.random' from '/home/redsteve/myenv2/lib/python3.11/site-packages/numpy/random/__init__.py'>

In [50]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [64]:
 q = np.arange(60).reshape(6,1,5,2) #four dimensions
q.ndim

4

In [65]:
q

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]]],


       [[[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]]],


       [[[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]]],


       [[[30, 31],
         [32, 33],
         [34, 35],
         [36, 37],
         [38, 39]]],


       [[[40, 41],
         [42, 43],
         [44, 45],
         [46, 47],
         [48, 49]]],


       [[[50, 51],
         [52, 53],
         [54, 55],
         [56, 57],
         [58, 59]]]])

In [73]:
A = np.arange(50).reshape(5,10)
A


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [71]:
B = np.arange(100).reshape(10,10)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [77]:
A @ B #matxit product of arrays(vectors)

array([[ 2850,  2895,  2940,  2985,  3030,  3075,  3120,  3165,  3210,
         3255],
       [ 7350,  7495,  7640,  7785,  7930,  8075,  8220,  8365,  8510,
         8655],
       [11850, 12095, 12340, 12585, 12830, 13075, 13320, 13565, 13810,
        14055],
       [16350, 16695, 17040, 17385, 17730, 18075, 18420, 18765, 19110,
        19455],
       [20850, 21295, 21740, 22185, 22630, 23075, 23520, 23965, 24410,
        24855]])