In [5]:
import numpy as np

a = np.arange(20).reshape(4, 5) # this will create an ndarray with 20 integers

a.ndim #displays the dimesion(axes) of the ndarray generated.
type(a)

numpy.ndarray

In [6]:
a.shape #size of the arrays in each dimensions

(4, 5)

In [11]:
a.size #number of element in the array

20

In [12]:
a.dtype #the data type of the element in the ndarray

dtype('int64')

In [13]:
a.itemsize #size of each element in the ndarray

8

In [7]:
a.data #buffer containing the actual elements.

In [9]:
b = np.array([2,3,4,5,3,12,65,32])
type(b)

numpy.ndarray

In [12]:
c = np.array([(1,2,6,54,65,54), (43,65,43,32,324,654), ("steve" , "muish", "mike", "fab", "school", 8)])
c

array([['1', '2', '6', '54', '65', '54'],
       ['43', '65', '43', '32', '324', '654'],
       ['steve', 'muish', 'mike', 'fab', 'school', '8']], dtype='<U21')

In [13]:
c.dtype

dtype('<U21')

In [22]:
d = np.empty((3,15))
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.empty((3,3))

array([[1.58218056e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [39]:
np.arange(.000001, 21.0000001, 1.5821)

array([1.0000000e-06, 1.5821010e+00, 3.1642010e+00, 4.7463010e+00,
       6.3284010e+00, 7.9105010e+00, 9.4926010e+00, 1.1074701e+01,
       1.2656801e+01, 1.4238901e+01, 1.5821001e+01, 1.7403101e+01,
       1.8985201e+01, 2.0567301e+01])

In [43]:
np.linspace(0,2,22) #22 numbers from 0 to 2.

array([0.        , 0.0952381 , 0.19047619, 0.28571429, 0.38095238,
       0.47619048, 0.57142857, 0.66666667, 0.76190476, 0.85714286,
       0.95238095, 1.04761905, 1.14285714, 1.23809524, 1.33333333,
       1.42857143, 1.52380952, 1.61904762, 1.71428571, 1.80952381,
       1.9047619 , 2.        ])